// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOGNFtrSWUqtoJ6gbpAtUUkbDNXaMjYT4',
    appId: '1:1073602423614:web:3b15d68e77cd60ed899a6f',
    messagingSenderId: '1073602423614',
    projectId: 'ajira-plus-e1007',
    authDomain: 'ajira-plus-e1007.firebaseapp.com',
    storageBucket: 'ajira-plus-e1007.firebasestorage.app',
    measurementId: 'G-WM46MK4TN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCupBRrWK88namiN6L2qRG5xUE5NR3DXTM',
    appId: '1:1073602423614:android:64853d62ee2f7747899a6f',
    messagingSenderId: '1073602423614',
    projectId: 'ajira-plus-e1007',
    storageBucket: 'ajira-plus-e1007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgcLkzklYhqAYEkZP5zwfHGoU9eIxyDc4',
    appId: '1:1073602423614:ios:ba4a696d4a38c4a1899a6f',
    messagingSenderId: '1073602423614',
    projectId: 'ajira-plus-e1007',
    storageBucket: 'ajira-plus-e1007.firebasestorage.app',
    iosBundleId: 'com.example.ajiraPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgcLkzklYhqAYEkZP5zwfHGoU9eIxyDc4',
    appId: '1:1073602423614:ios:ba4a696d4a38c4a1899a6f',
    messagingSenderId: '1073602423614',
    projectId: 'ajira-plus-e1007',
    storageBucket: 'ajira-plus-e1007.firebasestorage.app',
    iosBundleId: 'com.example.ajiraPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOGNFtrSWUqtoJ6gbpAtUUkbDNXaMjYT4',
    appId: '1:1073602423614:web:3b859089232c3124899a6f',
    messagingSenderId: '1073602423614',
    projectId: 'ajira-plus-e1007',
    authDomain: 'ajira-plus-e1007.firebaseapp.com',
    storageBucket: 'ajira-plus-e1007.firebasestorage.app',
    measurementId: 'G-EE7M6J7BRB',
  );
}
